# Generated by Django 4.2.30 on 2026-05-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(choices=[('daily', 'Daily pass'), ('weekly', 'Weekly'), ('season', 'Season (~3 months)')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='entitlement_type',
            field=models.CharField(choices=[('game_only', 'Game only'), ('game_and_streaming', 'Game + streaming'), ('streaming_only', 'Streaming only')], default='game_and_streaming', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='entertainment_platform.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', help_text='user | staff — staff may manage subscription plans via API', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_period',
            field=models.CharField(default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='entitlement_type',
            field=models.CharField(default='game_and_streaming', max_length=32),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='price_paid_afn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='purchase_phone_number',
            field=models.CharField(blank=True, default='', help_text='Mobile number recorded at purchase (same as account phone unless overridden later)', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_hours',
            field=models.IntegerField(help_text='Wall-clock access length (e.g. 24 for daily, 2160 for ~90 days)'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['billing_period', 'entitlement_type'], name='subscriptio_billing_d7694f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['entitlement_type'], name='user_subscr_entitle_86551f_idx'),
        ),
    ]
