# Generated by Django 4.2.30 on 2026-05-30 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entertainment_platform', '0005_user_languages'),
        ('xp_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyDraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('subscription', 'Subscription'), ('merch', 'Merchandise'), ('platform', 'Platform'), ('other', 'Other')], default='other', max_length=30)),
                ('prize_title', models.CharField(max_length=200)),
                ('prize_description', models.TextField(blank=True, default='')),
                ('prize_image_url', models.URLField(blank=True, default='')),
                ('entry_xp', models.PositiveIntegerField()),
                ('end_date', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('winner_count', models.PositiveIntegerField(default=1)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('drawn', 'Drawn'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lucky_draws_created', to='entertainment_platform.user')),
            ],
            options={
                'db_table': 'lucky_draws',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LuckyDrawEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('lucky_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lucky_draw.luckydraw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_draw_entries', to='entertainment_platform.user')),
                ('xp_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lucky_draw_entries', to='xp_management.xptransaction')),
            ],
            options={
                'db_table': 'lucky_draw_entries',
                'ordering': ['entered_at'],
            },
        ),
        migrations.CreateModel(
            name='LuckyDrawWinner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('announced_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='win_records', to='lucky_draw.luckydrawentry')),
                ('lucky_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='lucky_draw.luckydraw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_draw_wins', to='entertainment_platform.user')),
            ],
            options={
                'db_table': 'lucky_draw_winners',
                'ordering': ['rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='luckydrawwinner',
            constraint=models.UniqueConstraint(fields=('lucky_draw', 'rank'), name='unique_lucky_draw_winner_rank'),
        ),
        migrations.AddConstraint(
            model_name='luckydrawwinner',
            constraint=models.UniqueConstraint(fields=('lucky_draw', 'user'), name='unique_lucky_draw_winner_user'),
        ),
        migrations.AddIndex(
            model_name='luckydrawentry',
            index=models.Index(fields=['lucky_draw', 'entered_at'], name='lucky_draw__lucky_d_da052f_idx'),
        ),
        migrations.AddConstraint(
            model_name='luckydrawentry',
            constraint=models.UniqueConstraint(fields=('lucky_draw', 'user'), name='unique_lucky_draw_entry_per_user'),
        ),
        migrations.AddIndex(
            model_name='luckydraw',
            index=models.Index(fields=['status', 'end_date'], name='lucky_draws_status_5f91e8_idx'),
        ),
        migrations.AddIndex(
            model_name='luckydraw',
            index=models.Index(fields=['category', 'status'], name='lucky_draws_categor_65b3b6_idx'),
        ),
    ]
