# Generated by Django 4.2.30 on 2026-05-20 19:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entertainment_platform', '0005_user_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('watch', 'Watch'), ('pay', 'Pay'), ('win', 'Win'), ('share', 'Share'), ('platform', 'Platform')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_verification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xp_events',
                'ordering': ['event_code'],
            },
        ),
        migrations.CreateModel(
            name='XPRedemptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('xp_cost', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xp_redemption_items',
            },
        ),
        migrations.CreateModel(
            name='XPRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=150)),
                ('base_xp', models.IntegerField()),
                ('xp_formula_type', models.CharField(choices=[('flat', 'Flat'), ('per_unit', 'Per Unit'), ('percentage', 'Percentage'), ('tiered', 'Tiered')], default='flat', max_length=20)),
                ('xp_formula_param', models.JSONField(blank=True, default=dict)),
                ('daily_cap_xp', models.IntegerField(blank=True, null=True)),
                ('global_daily_cap', models.IntegerField(blank=True, null=True)),
                ('cooldown_seconds', models.IntegerField(default=0)),
                ('max_per_lifetime', models.IntegerField(blank=True, null=True)),
                ('expiry_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_rules_created', to='entertainment_platform.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='xp_management.xpevent')),
            ],
            options={
                'db_table': 'xp_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XPAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(default='system', max_length=100)),
                ('action_type', models.CharField(max_length=80)),
                ('target_entity', models.CharField(max_length=80)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_audit_actions', to='entertainment_platform.user')),
            ],
            options={
                'db_table': 'xp_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserXPWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_xp_earned', models.BigIntegerField(default=0)),
                ('available_xp', models.BigIntegerField(default=0)),
                ('redeemed_xp', models.BigIntegerField(default=0)),
                ('expired_xp', models.BigIntegerField(default=0)),
                ('xp_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=20)),
                ('tier_updated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_wallet', to='entertainment_platform.user')),
            ],
            options={
                'db_table': 'user_xp_wallet',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('expire', 'Expire'), ('bonus', 'Bonus'), ('reversal', 'Reversal')], max_length=20)),
                ('xp_amount', models.IntegerField()),
                ('base_xp', models.IntegerField(default=0)),
                ('multiplier_applied', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('balance_before', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='xp_management.xpevent')),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='xp_management.xptransaction')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='xp_management.xprule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='entertainment_platform.user')),
            ],
            options={
                'db_table': 'xp_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='xp_transact_user_id_92484a_idx'), models.Index(fields=['user', 'rule', 'created_at'], name='xp_transact_user_id_0600a3_idx'), models.Index(fields=['expires_at', 'status', 'is_expired'], name='xp_transact_expires_f0b2ac_idx')],
            },
        ),
    ]
